name: Java CI with Gradle

on:
  push:
    branches: [ release/* ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      platform:
        description: 'Choose the platform for the build'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
      fail-fast: false
      max-parallel: 4

    steps:
      # Checkout 代码
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'

      - name: Build with Gradle (JLink)
        run: ./gradlew clean build jpackage

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Upload JDK Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: javafx-devtools-${{ runner.os }}
          path: build/jpackage/
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
          body: |
            This is an automated release for the branch ${{ github.ref_name }}.
            Artifacts are uploaded for the following platforms:
            - Ubuntu
            - macOS
            - Windows